version: "3.7"
x-restart-policy: &restart_policy
  restart: unless-stopped

services:

  service:
    <<: *restart_policy
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /app/service
    ports:
      - "8080:8080"
    volumes:
      - ".env:/app/.env"
    depends_on:
      db:
        condition: service_healthy

  db:
    <<: *restart_policy
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-migrate:
    image: gomicro/goose:3.7.0
    volumes:
      - ./db/migrations:/migrations
    command: goose -s postgres "postgres://postgres@db:5432/postgres?sslmode=disable" up
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:

